import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className=" bg-slate-100 h-full">
      <main className="pt-40 pb-20 bg-slate-200"> {children}</main>
    </div>
  );
}
